// lib/legal-content.ts

// 定义支持的语言类型
type SupportedLocales = 'en' | 'zh' | 'tw' | 'hk';


export const lastUpdatedString = 'January 2026';

// ---------------------- Terms of Service (多语言) ----------------------
export const TERMS_TEMPLATES: Record<SupportedLocales, string> = {
  en: `
Welcome to Voo! These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and Voo Inc. ("we," "us," or "our") regarding your access to and use of the Voo website, mobile application, and related services (collectively, the "Platform").

By creating an account or using the Platform, you agree to comply with these Terms. If you do not agree, please do not use our services.

## 1. Description of Services
Voo is a marketplace connecting users seeking services ("Customers") with individuals or entities offering services ("Merchants"). The Platform serves solely as a neutral facilitator and is not a party to any service contracts directly between Customers and Merchants.

## 2. Account Registration
* You must be at least 18 years old to register as a Merchant.
* You represent that all information provided is accurate and current.
* You are responsible for maintaining the confidentiality of your login credentials.

## 3. Booking, Fees & Payments

### 3.1 Fees
* **Platform Service Fee:** To operate the Platform, we charge Merchants a service fee of **{{platformFee}}** on the total value of each completed booking.
* **Fee Allowance:** We support small businesses. Merchants receive a monthly fee allowance tier of **{{monthlyAllowance}}**. The Platform Service Fee applies only to earnings exceeding this amount per month.
* **Processing Fees:** For Platform-Managed Payments, third-party processing fees (e.g., Stripe) are deducted separately.

### 3.2 Booking Process
* **Pre-Authorization:** For Platform-Managed services, payment methods are authorized **{{prePayDays}} days** prior to the scheduled service date.
* **Payouts:** Funds are typically released to the Merchant 1 day after service completion, subject to any dispute holds.

## 4. Cancellation & Refunds

### 4.1 Merchant Cancellation
If a Merchant cancels a confirmed booking, they agree to pay a penalty fee equivalent to **{{cancelPenalty}} of the booking value** to compensate the Customer.

### 4.2 Customer Cancellation
* **Modification Window:** Customers may request changes or cancellation up to **{{prePayDays}} days** before the scheduled service date without penalty.
* **Late Cancellation:** Requests made within {{prePayDays}} days of the service are subject to the Merchant’s discretion.

## 5. Referral Program & Rewards

We offer a Referral Program to reward users who invite others to join Voo.

### 5.1 Eligibility & Calculation
* **Commission Rate:** Referrers may earn a commission equivalent to **{{referralPercent}}** of the booking value generated by their invitees.
* **Split Commission:** If a booking involves both an invited Merchant and an invited Customer, the commission pool is split equally (50/50) between the Merchant's Referrer and the Customer's Referrer.
* **Duration:** Referral commissions are valid for **{{referralMonths}} months** from the invitee's registration date.

### 5.2 Multi-Tier Distribution
To encourage community growth, commissions are distributed across two levels of referrers:
* **Direct Referrer:** The person who directly invited the user receives **{{directInviterShare}}** of the applicable commission.
* **Second-Tier Referrer:** The person who invited the Direct Referrer (if applicable) receives **{{secondInviterPercent}}** of the applicable commission.
* If there is no Second-Tier Referrer, the Direct Referrer receives the full applicable commission.

### 5.3 Limitations
* The total commission payout for any single booking shall not exceed {{referralPercent}}.
* You cannot refer yourself or create fake accounts to earn commissions. Violation will result in account termination and forfeiture of rewards.

## 6. Dispute Resolution
* **Window:** Customers may raise a dispute within **90 days** of the service date.
* **Process:** If the Merchant fails to respond to a dispute within **4 days**, the Customer's proposed adjustment will be automatically accepted.
* **Arbitration:** Voo's decision regarding disputes is final.

## 7. Limitation of Liability
Voo does not provide the services listed. We are not responsible for the quality, safety, or legality of services provided by Merchants. You assume all risks associated with offline interactions.

## 8. Contact Us
For questions, please contact us at: suppportvoo@gmail.com.
  `,

  zh: `
欢迎使用 Voo！本《用户服务协议》（以下简称“本条款”）构成您（“用户”、“您”）与 Voo Inc.（“我们”）之间关于您访问和使用 Voo 网站、移动应用程序及相关服务（统称“平台”）的具有法律约束力的协议。

通过创建账户或使用本平台，即表示您同意遵守本条款。如果您不同意，请勿使用我们的服务。

## 1. 服务说明
Voo 是一个连接寻求服务的用户（“客户”）与提供服务的个人或实体（“商家”）的市场平台。本平台仅作为中立的促进者，并非客户与商家之间任何直接服务合同的签约方。

## 2. 账户注册
* 您必须年满 18 岁才能注册成为商家。
* 您声明所提供的所有信息均准确且为最新信息。
* 您有责任维护您登录凭据的机密性。

## 3. 预订、费用与支付

### 3.1 费用
* **平台服务费：** 为了运营本平台，我们将对商家每笔已完成的预订，按预订总价值收取 **{{platformFee}}** 的服务费。
* **费用免额：** 我们支持小微企业。商家每月享有 **{{monthlyAllowance}}** 的服务费免除额度。平台服务费仅适用于每月超过此额度的收入部分。
* **处理费：** 对于由平台托管支付的交易，第三方支付处理费（例如 Stripe 费用）将单独扣除。

### 3.2 预订流程
* **预授权：** 对于由平台托管支付的服务，我们会在预定服务日期前 **{{prePayDays}} 天** 对支付方式进行预授权。
* **打款：** 资金通常会在服务完成后 1 天发放给商家，除非存在争议冻结。

## 4. 取消与退款

### 4.1 商家取消
如果商家取消已确认的预订，商家同意支付相当于**预订价值 {{cancelPenalty}}** 的违约金以补偿客户。

### 4.2 客户取消
* **修改窗口：** 客户可在预定服务日期前 **{{prePayDays}} 天** 申请更改或取消，无需支付罚金。
* **逾期取消：** 在服务日期前 {{prePayDays}} 天内提出的请求，将由商家自行决定是否接受。

## 5. 推荐计划与奖励

我们提供推荐计划以奖励邀请他人加入 Voo 的用户。

### 5.1 资格与计算
* **佣金比例：** 推荐人可获得相当于受邀人产生的预订价值 **{{referralPercent}}** 的金额作为佣金。
* **佣金拆分：** 如果一笔预订同时涉及受邀商家和受邀客户，佣金池将在商家的推荐人和客户的推荐人之间平均分配（50/50）。
* **有效期：** 推荐佣金的有效期为受邀人注册之日起 **{{referralMonths}} 个月**内。

### 5.2 多级分销
为了鼓励社区增长，佣金将在两个层级的推荐人之间分配：
* **直接推荐人：** 直接邀请该用户的人获得适用佣金的 **{{directInviterShare}}**。
* **二级推荐人：** 邀请了“直接推荐人”的人（如有）获得适用佣金的 **{{secondInviterPercent}}**。
* 如果不存在二级推荐人，则直接推荐人获得全部适用佣金。

### 5.3 限制
* 单笔预订支付的总佣金不得超过 {{referralPercent}}。
* 您不得推荐自己或创建虚假账户来赚取佣金。违规行为将导致账户终止和奖励没收。

## 6. 争议解决
* **时效：** 客户可在服务日期后的 **90 天** 内提出争议。
* **流程：** 如果商家未在 **4 天** 内对争议做出回应，客户提出的调整方案将被自动接受。
* **仲裁：** Voo 对争议的最终决定具有约束力。

## 7. 责任限制
Voo 不提供所列的服务。我们不对商家提供的服务的质量、安全性或合法性负责。您承担与线下互动相关的所有风险。
  `,

  tw: `
歡迎使用 Voo！本《服務條款》（以下簡稱「本條款」）構成您（「使用者」、「您」）與 Voo Inc.（「我們」）之間關於您存取和使用 Voo 網站、行動應用程式及相關服務（統稱「平台」）的具有法律約束力的協議。

透過建立帳戶或使用本平台，即表示您同意遵守本條款。如果您不同意，請勿使用我們的服務。

## 1. 服務說明
Voo 是一個連結尋求服務的使用者（「顧客」）與提供服務的個人或實體（「商家」）的市集平台。本平台僅作為中立的促進者，並非顧客與商家之間任何直接服務合約的當事人。

## 2. 帳戶註冊
* 您必須年滿 18 歲才能註冊成為商家。
* 您聲明所提供的所有資訊均準確且為最新資訊。
* 您有責任維護您登入憑證的機密性。

## 3. 預訂、費用與付款

### 3.1 費用
* **平台服務費：** 為維持平台營運，我們將對商家每筆已完成的預訂，按預訂總價值收取 **{{platformFee}}** 的服務費。
* **費用免額：** 我們支持微型企業。商家每月享有 **{{monthlyAllowance}}** 的服務費折抵額度。平台服務費僅適用於每月超過此額度的營收部分。
* **處理費：** 對於由平台託管付款的交易，第三方金流處理費（例如 Stripe 費用）將另行扣除。

### 3.2 預訂流程
* **預授權：** 對於由平台託管付款的服務，我們會在預定服務日期前 **{{prePayDays}} 天** 對付款方式進行預授權。
* **撥款：** 款項通常會在服務完成後 1 天發放給商家，除非存在爭議凍結。

## 4. 取消與退款

### 4.1 商家取消
如果商家取消已確認的預訂，商家同意支付相當於**預訂價值 {{cancelPenalty}}** 的違約金以補償顧客。

### 4.2 顧客取消
* **修改期限：** 顧客可在預定服務日期前 **{{prePayDays}} 天** 申請更改或取消，無需支付罰金。
* **逾期取消：** 在服務日期前 {{prePayDays}} 天內提出的請求，將由商家自行決定是否接受。

## 5. 推薦計劃與獎勵

我們提供推薦計劃以獎勵邀請他人加入 Voo 的使用者。

### 5.1 資格與計算
* **佣金比例：** 推薦人可獲得相當於受邀人產生的預訂價值 **{{referralPercent}}** 的金額作為佣金。
* **佣金分拆：** 如果一筆預訂同時涉及受邀商家和受邀顧客，佣金池將在商家的推薦人和顧客的推薦人之間平均分配（50/50）。
* **有效期：** 推薦佣金的有效期為受邀人註冊之日起 **{{referralMonths}} 個月**內。

### 5.2 多層級分銷
為了鼓勵社群成長，佣金將在兩個層級的推薦人之間分配：
* **直接推薦人：** 直接邀請該使用者的人獲得適用佣金的 **{{directInviterShare}}**。
* **二級推薦人：** 邀請了「直接推薦人」的人（如有）獲得適用佣金的 **{{secondInviterPercent}}**。
* 如果不存在二級推薦人，則直接推薦人獲得全部適用佣金。

### 5.3 限制
* 單筆預訂支付的總佣金不得超過 {{referralPercent}}。
* 您不得推薦自己或建立虛假帳戶來賺取佣金。違規行為將導致帳戶終止和獎勵沒收。

## 6. 爭議解決
* **時效：** 顧客可在服務日期後的 **90 天** 內提出爭議。
* **流程：** 如果商家未在 **4 天** 內對爭議做出回應，顧客提出的調整方案將被自動接受。
* **仲裁：** Voo 對爭議的最終決定具有約束力。

## 7. 責任限制
Voo 不提供所列的服務。我們不對商家提供的服務的品質、安全性或合法性負責。您承擔與線下互動相關的所有風險。  
`,

hk: `
歡迎使用 Voo！本《服務條款》（以下簡稱「本條款」）構成閣下（「用戶」、「閣下」）與 Voo Inc.（「我們」）之間關於閣下存取和使用 Voo 網站、流動應用程式及相關服務（統稱「平台」）的具法律約束力的協議。

透過建立帳戶或使用本平台，即表示閣下同意遵守本條款。如閣下不同意，請勿使用我們的服務。

## 1. 服務說明
Voo 是一個連結尋求服務的用戶（「顧客」）與提供服務的個人或實體（「商戶」）的市場平台。本平台僅作為中立的促進者，並非顧客與商戶之間任何直接服務合約的締約方。

## 2. 帳戶註冊
* 閣下必須年滿 18 歲才能註冊成為商戶。
* 閣下聲明所提供的所有資料均準確且為最新資料。
* 閣下有責任維護閣下登入憑證的機密性。

## 3. 預訂、費用與付款

### 3.1 費用
* **平台服務費：** 為維持平台營運，我們將對商戶每筆已完成的預訂，按預訂總價值收取 **{{platformFee}}** 的服務費。
* **費用免額：** 我們支持小型企業。商戶每月享有 **{{monthlyAllowance}}** 的服務費寬免額度。平台服務費僅適用於每月超過此額度的收入部分。
* **處理費：** 對於由平台託管付款的交易，第三方付款處理費（例如 Stripe 費用）將另行扣除。

### 3.2 預訂流程
* **預授權：** 對於由平台託管付款的服務，我們會在預定服務日期前 **{{prePayDays}} 天** 對付款方式進行預授權。
* **發放款項：** 款項通常會在服務完成後 1 天發放給商戶，除非存在爭議凍結。

## 4. 取消與退款

### 4.1 商戶取消
如商戶取消已確認的預訂，商戶同意支付相當於**預訂價值 {{cancelPenalty}}** 的罰款以補償顧客。

### 4.2 顧客取消
* **修改期限：** 顧客可在預定服務日期前 **{{prePayDays}} 天** 申請更改或取消，無需支付罰款。
* **逾期取消：** 在服務日期前 {{prePayDays}} 天內提出的請求，將由商戶自行決定是否接受。

## 5. 推薦計劃與獎勵

我們提供推薦計劃以獎勵邀請他人加入 Voo 的用戶。

### 5.1 資格與計算
* **佣金比例：** 推薦人可獲得相當於受邀人產生的預訂價值 **{{referralPercent}}** 的金額作為佣金。
* **佣金分配：** 如一筆預訂同時涉及受邀商戶和受邀顧客，佣金池將在商戶的推薦人和顧客的推薦人之間平均分配（50/50）。
* **有效期：** 推薦佣金的有效期為受邀人註冊之日起 **{{referralMonths}} 個月**內。

### 5.2 多層級分銷
為了鼓勵社群增長，佣金將在兩個層級的推薦人之間分配：
* **直接推薦人：** 直接邀請該用戶的人獲得適用佣金的 **{{directInviterShare}}**。
* **二級推薦人：** 邀請了「直接推薦人」的人（如有）獲得適用佣金的 **{{secondInviterPercent}}**。
* 如不存在二級推薦人，則直接推薦人獲得全部適用佣金。

### 5.3 限制
* 單筆預訂支付的總佣金不得超過 {{referralPercent}}。
* 閣下不得推薦自己或建立虛假帳戶來賺取佣金。違規行為將導致帳戶終止和獎勵沒收。

## 6. 爭議解決
* **時效：** 顧客可在服務日期後的 **90 天** 內提出爭議。
* **流程：** 如商戶未在 **4 天** 內對爭議做出回應，顧客提出的調整方案將被自動接受。
* **仲裁：** Voo 對爭議的最終決定具有約束力。

## 7. 責任限制
Voo 不提供所列的服務。我們不對商戶提供的服務的質素、安全性或合法性負責。閣下承擔與線下互動相關的所有風險。
  `
  };

// ---------------------- Privacy Policy (多语言) ----------------------
export const PRIVACY_TEMPLATES: Record<SupportedLocales, string> = {
  en: `
Welcome to Voo Pro, a service platform operated by Voo Dev LLC. Your privacy is important to us. This Privacy Policy explains how we collect, use, and protect your personal information when you use our app to book services.

## 1. Information We Collect

### 1.1 Personal Information
* Name
* Email address
* Phone number
* Home or service location
* Payment information (processed securely by Stripe)

### 1.2 Service Usage Information
* Booking history
* Communication with service providers
* Ratings and reviews

### 1.3 Device & App Usage Information
* Device type and operating system
* IP address
* App usage data (e.g., interactions, preferences)

### 1.4 Cookies & Tracking Technologies
We use Google services for analytics and advertising, which may collect information through cookies and similar tracking technologies.

## 2. How We Use Your Information
* Provide and manage service bookings
* Connect users with service providers
* Process payments securely via Stripe
* Improve and personalize user experience
* Send service updates and promotional offers
* Ensure security and prevent fraud

## 3. How We Share Your Information
We do not sell your personal information. However, we may share it with:
* **Service Providers:** To facilitate bookings and communication
* **Stripe:** For secure payment processing
* **Google Services:** For analytics and app performance optimization
* **Legal Authorities:** If required by law or for fraud prevention

## 4. Data Security
We use industry-standard security measures to protect your data. However, no method of transmission over the internet is 100% secure. We recommend users take necessary precautions.

## 5. Your Rights & Choices
* Access, update, or delete your personal information
* Opt out of marketing communications
* Disable cookies via your browser settings

## 6. Third-Party Links & Services
Voo Pro may contain links to third-party websites or services, such as Google login. We are not responsible for their privacy practices and encourage users to review their policies.

## 7. Children's Privacy
Voo Pro is not intended for users under the age of 13. If we discover that a child's personal data has been collected, we will delete it immediately.

## 8. Data Retention
We retain user data for as long as necessary to provide our services. If you delete your account, we will remove your personal information, except where retention is required by law.

## 9. Changes to This Policy
We may update this Privacy Policy periodically. Users will be notified of significant changes.
`,
  
  zh: `
欢迎使用 Voo Pro，这是由 Voo Dev LLC 运营的服务平台。您的隐私对我们至关重要。本《隐私政策》旨在说明当您使用我们的 App 预订服务时，我们如何收集、使用和保护您的个人信息。

## 1. 我们收集的信息

### 1.1 个人信息
* 姓名
* 电子邮箱地址
* 电话号码
* 家庭或服务地址
* 支付信息（由 Stripe 安全处理）

### 1.2 服务使用信息
* 预订历史
* 与服务提供商的沟通记录
* 评分与评论

### 1.3 设备与 App 使用信息
* 设备类型和操作系统
* IP 地址
* App 使用数据（例如：交互记录、偏好设置）

### 1.4 Cookie 与追踪技术
我们使用 Google 服务进行分析和广告推广，这些服务可能会通过 Cookie 和类似的追踪技术收集信息。

## 2. 我们如何使用您的信息
* 提供和管理服务预订
* 连接用户与服务提供商
* 通过 Stripe 安全处理支付
* 改进和个性化用户体验
* 发送服务更新和促销优惠
* 确保安全性并防止欺诈

## 3. 我们如何共享您的信息
我们不会出售您的个人信息。但是，我们可能会与以下方共享信息：
* **服务提供商：** 用于协助预订和沟通
* **Stripe：** 用于安全支付处理
* **Google 服务：** 用于分析和 App 性能优化
* **法律机构：** 如法律要求或为了防止欺诈

## 4. 数据安全
我们采用行业标准的安全措施来保护您的数据。然而，互联网上的传输方法并非 100% 安全。我们建议用户采取必要的预防措施。

## 5. 您的权利与选择
* 访问、更新或删除您的个人信息
* 选择退出营销通讯
* 通过浏览器设置禁用 Cookie

## 6. 第三方链接与服务
Voo Pro 可能包含指向第三方网站或服务（如 Google 登录）的链接。我们不对其隐私惯例负责，并鼓励用户查看其政策。

## 7. 儿童隐私
Voo Pro 不面向 13 岁以下的用户。如果我们发现收集了儿童的个人数据，我们将立即将其删除。

## 8. 数据保留
我们会在提供服务所需的期间内保留用户数据。如果您删除账户，我们将移除您的个人信息，除非法律要求保留。

## 9. 本政策的变更
我们可能会定期更新本《隐私政策》。如有重大变更，我们将通知用户。
  `,

  tw: `
歡迎使用 Voo Pro，這是由 Voo Dev LLC 營運的服務平台。您的隱私對我們至關重要。本《隱私權政策》旨在說明當您使用我們的應用程式（App）預訂服務時，我們如何蒐集、使用和保護您的個人資訊。

## 1. 我們蒐集的資訊

### 1.1 個人資訊
* 姓名
* 電子郵件地址
* 電話號碼
* 住家或服務地點
* 付款資訊（由 Stripe 安全處理）

### 1.2 服務使用資訊
* 預訂紀錄
* 與服務提供者的溝通紀錄
* 評分與評論

### 1.3 裝置與 App 使用資訊
* 裝置類型和作業系統
* IP 位址
* App 使用數據（例如：互動紀錄、偏好設定）

### 1.4 Cookies 與追蹤技術
我們使用 Google 服務進行分析和廣告推廣，這些服務可能會透過 Cookies 和類似的追蹤技術蒐集資訊。

## 2. 我們如何使用您的資訊
* 提供和管理服務預訂
* 連結使用者與服務提供者
* 透過 Stripe 安全處理付款
* 改進和個人化使用者體驗
* 發送服務更新和促銷優惠
* 確保安全性並防止詐欺

## 3. 我們如何分享您的資訊
我們不會出售您的個人資訊。但是，我們可能會與以下方分享資訊：
* **服務提供者：** 用於協助預訂和溝通
* **Stripe：** 用於安全付款處理
* **Google 服務：** 用於分析和 App 效能最佳化
* **法律機構：** 如法律要求或為了防止詐欺

## 4. 資料安全
我們採用業界標準的安全措施來保護您的資料。然而，網際網路上的傳輸方法並非 100% 安全。我們建議使用者採取必要的預防措施。

## 5. 您的權利與選擇
* 存取、更新或刪除您的個人資訊
* 選擇退出行銷通訊
* 透過瀏覽器設定停用 Cookies

## 6. 第三方連結與服務
Voo Pro 可能包含指向第三方網站或服務（如 Google 登入）的連結。我們不對其隱私慣例負責，並鼓勵使用者查看其政策。

## 7. 兒童隱私
Voo Pro 不針對 13 歲以下的使用者。如果我們發現蒐集了兒童的個人資料，我們將立即將其刪除。

## 8. 資料保留
我們會在提供服務所需的期間內保留使用者資料。如果您刪除帳戶，我們將移除您的個人資訊，除非法律要求保留。

## 9. 本政策的變更
我們可能會定期更新本《隱私權政策》。如有重大變更，我們將通知使用者。
  `,

  hk: `
歡迎使用 Voo Pro，這是由 Voo Dev LLC 營運的服務平台。閣下的私隱對我們至關重要。本《私隱政策》旨在說明當閣下使用我們的應用程式（App）預訂服務時，我們如何收集、使用和保護閣下的個人資料。

## 1. 我們收集的資料

### 1.1 個人資料
* 姓名
* 電郵地址
* 電話號碼
* 住宅或服務地點
* 付款資訊（由 Stripe 安全處理）

### 1.2 服務使用資料
* 預訂紀錄
* 與服務提供者的通訊紀錄
* 評分與評論

### 1.3 裝置與 App 使用資料
* 裝置類型和作業系統
* IP 位址
* App 使用數據（例如：互動紀錄、偏好設定）

### 1.4 Cookies 與追蹤技術
我們使用 Google 服務進行分析和廣告推廣，這些服務可能會透過 Cookies 和類似的追蹤技術收集資料。

## 2. 我們如何使用閣下的資料
* 提供和管理服務預訂
* 連結用戶與服務提供者
* 透過 Stripe 安全處理付款
* 改進和個人化用戶體驗
* 發送服務更新和推廣優惠
* 確保安全性並防止欺詐

## 3. 我們如何分享閣下的資料
我們不會出售閣下的個人資料。但是，我們可能會與以下方分享資料：
* **服務提供者：** 用於協助預訂和溝通
* **Stripe：** 用於安全付款處理
* **Google 服務：** 用於分析和 App 效能最佳化
* **法律機構：** 如法律要求或為了防止欺詐

## 4. 資料保安
我們採用業界標準的保安措施來保護閣下的資料。然而，互聯網上的傳輸方法並非 100% 安全。我們建議用戶採取必要的預防措施。

## 5. 閣下的權利與選擇
* 查閱、更新或刪除閣下的個人資料
* 選擇退出營銷通訊
* 透過瀏覽器設定停用 Cookies

## 6. 第三方連結與服務
Voo Pro 可能包含指向第三方網站或服務（如 Google 登入）的連結。我們不對其私隱慣例負責，並鼓勵用戶查看其政策。

## 7. 兒童私隱
Voo Pro 不面向 13 歲以下的用戶。如果我們發現收集了兒童的個人資料，我們將立即將其刪除。

## 8. 資料保留
我們會在提供服務所需的期間內保留用戶資料。如果閣下刪除帳戶，我們將移除閣下的個人資料，除非法律要求保留。

## 9. 本政策的變更
我們可能會定期更新本《私隱政策》。如有重大變更，我們將通知用戶。
  `
};


export const TERMS_OF_SERVICE_TEMPLATE = `
# Terms of Service

**Last Updated:** January 2026

Welcome to Voo! These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and Voo Inc. ("we," "us," or "our") regarding your access to and use of the Voo website, mobile application, and related services (collectively, the "Platform").

By creating an account or using the Platform, you agree to comply with these Terms. If you do not agree, please do not use our services.

## 1. Description of Services
Voo is a marketplace connecting users seeking services ("Customers") with individuals or entities offering services ("Merchants"). The Platform serves solely as a neutral facilitator and is not a party to any service contracts directly between Customers and Merchants.

## 2. Account Registration
* You must be at least 18 years old to register as a Merchant.
* You represent that all information provided is accurate and current.
* You are responsible for maintaining the confidentiality of your login credentials.

## 3. Booking, Fees & Payments

### 3.1 Fees
* **Platform Service Fee:** To operate the Platform, we charge Merchants a service fee of **{{platformFee}}** on the total value of each completed booking.
* **Fee Allowance:** We support small businesses. Merchants receive a monthly fee allowance tier of **{{monthlyAllowance}}**. The Platform Service Fee applies only to earnings exceeding this amount per month.
* **Processing Fees:** For Platform-Managed Payments, third-party processing fees (e.g., Stripe) are deducted separately.

### 3.2 Booking Process
* **Pre-Authorization:** For Platform-Managed services, payment methods are authorized **{{prePayDays}} days** prior to the scheduled service date.
* **Payouts:** Funds are typically released to the Merchant 1 day after service completion, subject to any dispute holds.

## 4. Cancellation & Refunds

### 4.1 Merchant Cancellation
If a Merchant cancels a confirmed booking, they agree to pay a penalty fee equivalent to **{{cancelPenalty}} of the booking value** to compensate the Customer.

### 4.2 Customer Cancellation
* **Modification Window:** Customers may request changes or cancellation up to **{{prePayDays}} days** before the scheduled service date without penalty.
* **Late Cancellation:** Requests made within {{prePayDays}} days of the service are subject to the Merchant’s discretion.

## 5. Referral Program & Rewards

We offer a Referral Program to reward users who invite others to join Voo.

### 5.1 Eligibility & Calculation
* **Commission Rate:** Referrers may earn a commission equivalent to **{{referralPercent}}** of the booking value generated by their invitees.
* **Split Commission:** If a booking involves both an invited Merchant and an invited Customer, the commission pool is split equally (50/50) between the Merchant's Referrer and the Customer's Referrer.
* **Duration:** Referral commissions are valid for **{{referralMonths}} months** from the invitee's registration date.

### 5.2 Multi-Tier Distribution
To encourage community growth, commissions are distributed across two levels of referrers:
* **Direct Referrer:** The person who directly invited the user receives **{{directInviterShare}}** of the applicable commission.
* **Second-Tier Referrer:** The person who invited the Direct Referrer (if applicable) receives **{{secondInviterPercent}}** of the applicable commission.
* If there is no Second-Tier Referrer, the Direct Referrer receives the full applicable commission.

### 5.3 Limitations
* The total commission payout for any single booking shall not exceed {{referralPercent}}.
* You cannot refer yourself or create fake accounts to earn commissions. Violation will result in account termination and forfeiture of rewards.

## 6. Dispute Resolution
* **Window:** Customers may raise a dispute within **90 days** of the service date.
* **Process:** If the Merchant fails to respond to a dispute within **4 days**, the Customer's proposed adjustment will be automatically accepted.
* **Arbitration:** Voo's decision regarding disputes is final.

## 7. Limitation of Liability
Voo does not provide the services listed. We are not responsible for the quality, safety, or legality of services provided by Merchants. You assume all risks associated with offline interactions.

## 8. Contact Us
For questions, please contact us at: suppportvoo@gmail.com.
`;

export const PRIVACY_POLICY = `
# Privacy Policy

**Last Updated:** January 2026

Voo ("we," "our," or "us") is committed to protecting your privacy.

## 1. Information We Collect
* **Account Data:** Name, email, phone number, and profile photo.
* **Payment Information:** Processed securely by Stripe. We do not store full credit card numbers.
* **Usage Data:** Device info, IP address, and interactions on the platform.

## 2. How We Use Your Information
We use your data to facilitate bookings, process payments (including fee calculations), verify identities, and resolve disputes.

## 3. Data Sharing
We share data with trusted partners like **Stripe** (payments), **Google/Firebase** (hosting/auth), and **Algolia** (search) solely for operational purposes. We do not sell your personal data.

## 4. Your Rights
You may request access to, correction of, or deletion of your personal data by contacting support@voo.app.
`;